standalone.xml commented jsf line

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -287,20 +287,20 @@ function start() {
   else
     echo "Starting $cartridge_type cartridge"
 
- #   ${BPMS_BIN_DIR}/standalone.sh > ${OPENSHIFT_TMP_DIR}/${cartridge_type}.log 2>&1 &
- #   PROCESS_ID=$!
- #   echo "$PROCESS_ID" > ${BPMS_PID_FILE}
+    ${BPMS_BIN_DIR}/standalone.sh > ${OPENSHIFT_TMP_DIR}/${cartridge_type}.log 2>&1 &
+    PROCESS_ID=$!
+    echo "$PROCESS_ID" > ${BPMS_PID_FILE}
 
- #   rc=0
- #   ishttpup || rc=$?
- #   if [ $rc -eq 1 ]; then
- #     echo "Timed out waiting for http listening port for $cartridge_type process"
- #     exit 1
- #   elif [ $rc -eq 2 ]; then
- #     echo "$cartridge_type process failed to start"
- #     exit 2
- #   fi
- #   waitondeployments
+    rc=0
+    ishttpup || rc=$?
+    if [ $rc -eq 1 ]; then
+      echo "Timed out waiting for http listening port for $cartridge_type process"
+      exit 1
+    elif [ $rc -eq 2 ]; then
+      echo "$cartridge_type process failed to start"
+      exit 2
+    fi
+    waitondeployments
   fi
 }
 
